version: 2

models:
  - name: bid_fact
    description: >
      Comprehensive fact table containing all job application bidding data from the Upwork marketplace.
      This table captures the complete bidding lifecycle including freelancer applications, client responses,
      ATS workflow, connects usage, boosted proposals, and first response metrics.
    columns:
      # Primary Key
      - name: agora_bid_id
        description: Unique identifier for the bid in Agora system
        tests:
          - unique
          - not_null
          
      # Essential Keys
      - name: post_key
        description: Surrogate key for job post dimension
        tests:
          - not_null
          
      - name: freelancer_key
        description: Surrogate key for freelancer dimension
        tests:
          - not_null
          
      # Essential Business Fields
      - name: bid_date
        description: Date when bid was submitted
        tests:
          - not_null
          
      - name: dw_active_flag
        description: Whether record is active in data warehouse
        tests:
          - not_null

 