name: 'aps_dbt_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'aps_dbt_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  aps_dbt_demo:
    +materialized: table
    +tags: ["watson_staging"]
    staging:
      +materialized: view
      +tags: ["staging", "watson"]
    marts:
      +materialized: table  
      +tags: ["marts", "watson"]

# Project variables  
vars:
  timezone: 'UTC'
  plt_database: "{{ env_var('PLT_DATABASE', 'SHASTA_SDC_UPWORK') }}"
  tgt_database: "{{ env_var('TGT_DATABASE', 'SBX_RISHISRIVASTAVA_DM13471_SHASTA_SDC_DPS') }}"
  pub_database: "{{ env_var('PUB_DATABASE', 'SHASTA_SDC_PUBLISHED') }}" 