name: 'aps_dbt_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'aps_dbt_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs
models:
  aps_dbt_demo:
    # Config indicated by + and applies to all files under models/
    +materialized: table
    staging:
      +materialized: view
      +tags: ["staging"]
    intermediate:
      +materialized: view  
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +tags: ["marts"]
      product:
        +materialized: table
        +tags: ["product", "marts"]

# Configure seeds
seeds:
  aps_dbt_demo:
    +quote_columns: false

# Configure snapshots
snapshots:
  aps_dbt_demo:
    +target_schema: snapshots

# Configure tests
tests:
  aps_dbt_demo:
    +store_failures: true

# Variables for bid_fact POC
vars:
  # The lookback period for bid processing (days)
  bid_lookback_days: 180
  # Timezone for date calculations
  timezone: 'UTC'
  # Environment-specific database references
  plt_database: "{{ env_var('PLT_DATABASE', 'SHASTA_SDC_UPWORK') }}"
  tgt_database: "{{ env_var('TGT_DATABASE', 'SBX_RISHISRIVASTAVA_DM13471_SHASTA_SDC_DPS') }}"
  pub_database: "{{ env_var('PUB_DATABASE', 'SHASTA_SDC_PUBLISHED') }}" 