version: 2

sources:
  # Platform database sources
  - name: contracts
    description: Contracts and related data
    database: "{{ var('plt_database') }}"
    schema: contracts
    tables:
      - name: hourly_limit_terms
        description: Hourly contract limit terms
      - name: contracts
        description: Contract data with status information
      - name: terms
        description: Contract terms data

  - name: openings
    description: Job openings and related data
    database: "{{ var('plt_database') }}"
    schema: openings
    tables:
      - name: openings
        description: Main job openings table
      - name: qualifications
        description: Job opening qualifications and requirements
      - name: annotations_custom_fields
        description: Custom annotations for job posts

  - name: openings_extra
    description: Additional job opening data
    database: "{{ var('plt_database') }}"
    schema: openings_extra
    tables:
      - name: openings_extra
        description: Extended job opening attributes

  - name: odb2_odesk_db
    description: Legacy ODesk database tables
    database: "{{ var('plt_database') }}"
    schema: odb2_odesk_db
    tables:
      - name: companies
        description: Company information from legacy system
      - name: agencies
        description: Agency information from legacy system
      - name: reasons
        description: Reason codes and descriptions

  - name: catalogdb
    description: Catalog database with project information
    database: "{{ var('plt_database') }}"
    schema: catalogdb
    tables:
      - name: project
        description: Project dimension data

  - name: scheduled_rate_increases
    description: Scheduled Rate Increases (SRI) data
    database: "{{ var('plt_database') }}"
    schema: scheduled_rate_increases
    tables:
      - name: planned_rate_increases
        description: Planned rate increases for contracts

  - name: bring_your_own
    description: Bring Your Own (BYO) relationship data
    database: "{{ var('plt_database') }}"
    schema: bring_your_own
    tables:
      - name: registration_invitations
        description: BYO registration invitations

  - name: directory
    description: Directory and organization data
    database: "{{ var('plt_database') }}"
    schema: directory
    tables:
      - name: organizations
        description: Organization directory

  - name: wms_offers
    description: Workforce Management System offers
    database: "{{ var('plt_database') }}"
    schema: wms_offers
    tables:
      - name: offers
        description: Job offers data
      - name: events
        description: Offer events and state changes

  - name: client_ads
    description: Client advertisements and pricing
    database: "{{ var('plt_database') }}"
    schema: client_ads
    tables:
      - name: ad_price_calculation
        description: Featured job pricing calculations
      - name: ad_status_history
        description: Ad status change history
      - name: ad
        description: Advertisement data

  - name: geods
    description: Geographic and location data
    database: "{{ var('plt_database') }}"
    schema: geods
    tables:
      - name: postal_code
        description: Postal code location data
      - name: area
        description: Geographic area data
      - name: city
        description: City location data

  - name: odesk_bpa_odesk_bp
    description: ODesk business process data
    database: "{{ var('plt_database') }}"
    schema: odesk_bpa_odesk_bp
    tables:
      - name: aes
        description: Account Executive data

  - name: finance_apps
    description: Finance applications data
    database: "{{ var('plt_database') }}"
    schema: finance_apps
    tables:
      - name: xxeo_pf_lkp_internal_ae_v
        description: Internal Account Executive lookup

  - name: cltvv2
    description: Customer Lifetime Value v2 data
    database: "{{ var('plt_database') }}"
    schema: cltvv2
    tables:
      - name: openings
        description: CLTV openings analysis

  - name: tns_datamart_tns_device_mgmt
    description: TNS device management data
    database: "{{ var('plt_database') }}"
    schema: tns_datamart_tns_device_mgmt
    tables:
      - name: device_ids
        description: Device ID tracking data

  # Target database sources (published dimensions)
  - name: sherlock
    description: Sherlock published dimension tables
    database: "{{ var('tgt_database') }}"
    schema: sherlock
    tables:
      - name: match_fjp_ltv
        description: Match FJP lifetime value data
      - name: post_dim
        description: Job post dimension table
      - name: client_dim
        description: Client dimension table
      - name: quality_segment_dim
        description: Quality segment dimension table

  - name: watson
    description: Watson staging schema (for incremental operations)
    database: "{{ var('tgt_database') }}"
    schema: watson
    tables:
      - name: stg_tns_device_mgmt_device_ids
        description: Staged TNS device management data (for incremental loads) 